"""Known official websites for Israeli local authorities."""

from __future__ import annotations

KNOWN_SITES: dict[str, str] = {
    "אום אל-פחם": "https://www.umelfahem.muni.il",
    "אופקים": "https://www.ofakim.muni.il",
    "אור יהודה": "https://www.or-yehuda.muni.il",
    "אור עקיבא": "https://www.orakiva.muni.il",
    "אילת": "https://www.eilat.muni.il",
    "טירה": "https://www.tiramunicipal.co.il",
    "אלעד": "https://www.elad.muni.il",
    "אריאל": "https://www.ariel.muni.il",
    "אשדוד": "https://www.ashdod.muni.il",
    "אשקלון": "https://www.ashkelon.muni.il",
    "באקה אל-גרביה": "https://www.baqa-west.muni.il",
    "באר שבע": "https://www.beer-sheva.muni.il",
    "בית שמש": "https://www.bet-shemesh.muni.il",
    "בית שאן": "https://www.bet-shean.muni.il",
    "ביתר עילית": "https://www.beitar-illit.muni.il",
    "בני ברק": "https://www.bnei-brak.muni.il",
    "בת ים": "https://www.bat-yam.muni.il",
    "גבעת שמואל": "https://www.givat-shmuel.muni.il",
    "גבעתיים": "https://www.givatayim.muni.il",
    "דימונה": "https://www.dimona.muni.il",
    "הוד השרון": "https://www.hod-hasharon.muni.il",
    "הרצלייה": "https://www.herzliya.muni.il",
    "הרצליה": "https://www.herzliya.muni.il",
    "חדרה": "https://www.hadera.muni.il",
    "חולון": "https://www.holon.muni.il",
    "חיפה": "https://www.haifa.muni.il",
    "טבריה": "https://www.tiberias.muni.il",
    "טייבה": "https://www.tayibe.muni.il",
    "טירת כרמל": "https://www.tirat-carmel.muni.il",
    "טמרה": "https://www.tamra.muni.il",
    "יבנה": "https://www.yavne.muni.il",
    "יהוד-מונוסון": "https://www.yehud-monosson.muni.il",
    "יקנעם עילית": "https://www.yoqneam.muni.il",
    "ירושלים": "https://www.jerusalem.muni.il",
    "כפר יונה": "https://www.kfar-yona.muni.il",
    "כפר סבא": "https://www.kfar-saba.muni.il",
    "כפר קאסם": "https://www.kfar-qasem.muni.il",
    "כרמיאל": "https://www.karmiel.muni.il",
    "לוד": "https://www.lod.muni.il",
    "מגדל העמק": "https://www.migdal-haemek.muni.il",
    "מודיעין-מכבים-רעות": "https://www.modiin.muni.il",
    "מודיעין עילית": "https://www.modiin-illit.muni.il",
    "מעלה אדומים": "https://www.m-e.muni.il",
    "מעלות-תרשיחא": "https://www.maltar.muni.il",
    "נהרייה": "https://www.nahariya.muni.il",
    "נס ציונה": "https://www.ness-ziona.muni.il",
    "נצרת": "https://www.nazareth.muni.il",
    "נוף הגליל": "https://www.nof-hagalil.muni.il",
    "נשר": "https://www.nesher.muni.il",
    "נתיבות": "https://www.netivot.muni.il",
    "נתניה": "https://www.netanya.muni.il",
    "סח'נין": "https://www.sakhnin.muni.il",
    "עפולה": "https://www.afula.muni.il",
    "עראבה": "https://www.arraba.muni.il",
    "ערד": "https://www.arad.muni.il",
    "פתח תקווה": "https://www.petah-tikva.muni.il",
    "צפת": "https://www.zefat.muni.il",
    "קלנסווה": "https://www.qalansawe.muni.il",
    "קריית אונו": "https://www.kiryatono.muni.il",
    "קריית אתא": "https://www.kiryat-ata.muni.il",
    "קריית ביאליק": "https://www.qbialik.org.il",
    "קריית גת": "https://www.kiryat-gat.muni.il",
    "קריית ים": "https://www.kiryat-yam.muni.il",
    "קריית מוצקין": "https://www.kiryat-motzkin.muni.il",
    "קריית מלאכי": "https://www.kiryat-malachi.muni.il",
    "קריית שמונה": "https://www.k-shmona.muni.il",
    "ראש העין": "https://www.r-ein.muni.il",
    "ראשון לציון": "https://www.rishonlezion.muni.il",
    "רהט": "https://www.rahat.muni.il",
    "רחובות": "https://www.rehovot.muni.il",
    "רמלה": "https://www.ramla.muni.il",
    "רמת גן": "https://www.ramat-gan.muni.il",
    "רמת השרון": "https://www.ramat-hasharon.muni.il",
    "רעננה": "https://www.raanana.muni.il",
    "שדרות": "https://www.sderot.muni.il",
    "שפרעם": "https://www.shefaram.muni.il",
    "תל אביב -יפו": "https://www.tel-aviv.gov.il",
    "תל אביב-יפו": "https://www.tel-aviv.gov.il",
    "באר יעקב": "https://www.b-y.muni.il",
    "גני תקווה": "https://www.ganey-tikva.muni.il",
    "חריש": "https://www.harish.muni.il",
    "כפר קרע": "https://www.kfar-kara.muni.il",
    "מגאר": "https://www.mgr.org.il",
    "עכו": "https://www.akko.muni.il",
    "אבן יהודה": "https://www.even-yehuda.muni.il",
    "אזור": "https://www.azor.muni.il",
    "גדרה": "https://www.gedera.muni.il",
    "גן יבנה": "https://www.ganyavne.muni.il",
    "זכרון יעקב": "https://www.zichron.org.il",
    "מבשרת ציון": "https://www.m-tzion.org.il",
    "מזכרת בתיה": "https://www.mazkeret-batya.muni.il",
    "פרדס חנה-כרכור": "https://www.pardes-hana-karkur.muni.il",
    "קדימה-צורן": "https://www.kadima-zoran.muni.il",
    "קריית טבעון": "https://www.tivon.muni.il",
    "שוהם": "https://www.shoham.muni.il",
    "תל מונד": "https://www.tel-mond.muni.il",
    "צור הדסה": "https://www.tsur-hadassah.muni.il",
    "גבעת זאב": "https://www.givat-zeev.muni.il",
    "אורנית": "https://www.oraniit.muni.il",
    "אלפי מנשה": "https://www.alfe-menashe.muni.il",
    "אפרת": "https://www.efrat.muni.il",
    "קצרין": "https://www.qatzrin.muni.il",
    "להבים": "https://www.lehavim.muni.il",
    "מיתר": "https://www.meitar.muni.il",
    "עומר": "https://www.omer.muni.il",
    "מצפה רמון": "https://www.mizpe-ramon.muni.il",
    "ירוחם": "https://www.yeruham.muni.il",
    "כפר ורדים": "https://www.kfar-veradim.muni.il",
    "מטולה": "https://www.metula.muni.il",
    "סביון": "https://www.savyon.muni.il",
    "כפר שמריהו": "https://www.kfar-shmaryahu.muni.il",
    "בנימינה-גבעת עדה": "https://www.binyamina-givatada.muni.il",
    "חצור הגלילית": "https://www.hatzor.org.il",
    "שלומי": "https://www.shlomi.muni.il",
    "כוכב יאיר": "https://www.kokhav-yair.muni.il",
    "קריית עקרון": "https://www.kiryat-ekron.muni.il",
    "ראש פינה": "https://www.rosh-pina.muni.il",
    "רמת ישי": "https://www.ramat-yishai.muni.il",
    "אשכול": "https://www.eshkol.info",
    "באר טוביה": "https://www.b-t.org.il",
    "ברנר": "https://www.brener.org.il",
    "גזר": "https://www.gezer.org.il",
    "דרום השרון": "https://www.drom-hasharon.org.il",
    "הגליל העליון": "https://www.galil-elion.org.il",
    "הגליל התחתון": "https://www.glt.org.il",
    "חוף הכרמל": "https://www.hof-hacarmel.org.il",
    "חוף השרון": "https://www.hof-hasharon.org.il",
    "לב השרון": "https://www.lev-hasharon.muni.il",
    "מטה יהודה": "https://www.m-yehuda.org.il",
    "מטה בנימין": "https://www.binyamin.org.il",
    "עמק חפר": "https://www.hefer.org.il",
    "עמק יזרעאל": "https://www.emekyizrael.org.il",
    "עמק הירדן": "https://www.emekhayarden.org.il",
    "משגב": "https://www.misgav.org.il",
    "מגידו": "https://www.megido.org.il",
    "מנשה": "https://www.menashe.co.il",
    "מרום הגליל": "https://www.merom-hagalil.org.il",
    "שער הנגב": "https://www.sng.org.il",
    "שדות נגב": "https://www.sdotnegev.org.il",
    "חוף אשקלון": "https://www.hof-ashkelon.org.il",
    "חבל מודיעין": "https://www.hevelmodiin.org.il",
    "זבולון": "https://www.zvulun.org.il",
    "מטה אשר": "https://www.mateh-asher.org.il",
    "רמת נגב": "https://www.ramatnegev.org.il",
    "תמר": "https://www.tamar.org.il",
    "הערבה התיכונה": "https://www.arava.co.il",
    "חבל אילות": "https://www.eilot.org.il",
    "גוש עציון": "https://www.gush-etzion.org.il",
    "שומרון": "https://www.shomron.org.il",
}
