from __future__ import annotations

import json
from datetime import datetime

from sqlalchemy.orm import Session

from app.catalogs import city_coords
from app.models import Service, ServiceSource


def _svc(**kwargs) -> Service:
    city = kwargs.get("city", "")
    coords = city_coords(city)
    if coords and not kwargs.get("lat"):
        kwargs["lat"], kwargs["lng"] = coords
    kwargs.setdefault("status", "approved")
    kwargs.setdefault("authority", "seed")
    kwargs.setdefault("confidence", "high")
    kwargs.setdefault("last_updated", datetime.utcnow())
    kwargs.setdefault("last_verified", datetime.utcnow())
    if isinstance(kwargs.get("addiction_types"), list):
        kwargs["addiction_types"] = json.dumps(kwargs["addiction_types"], ensure_ascii=False)
    if isinstance(kwargs.get("languages"), list):
        kwargs["languages"] = json.dumps(kwargs["languages"], ensure_ascii=False)
    return Service(**kwargs)


SEED_SERVICES: list[dict] = [
    {
        "external_id": "seed:eran-1201",
        "name": "ער״ן — קו חירום ארצי",
        "org_type": "public",
        "kind": "hotline",
        "city": "ארצי",
        "district": "national",
        "phone": "1201",
        "phone2": "052-8451201 (וואטסאפ)",
        "website": "https://www.eran.org.il/",
        "hours": "24/7",
        "cost_type": "free",
        "cost_info": "חינם, אנונימי",
        "eligibility": "כל אדם במצוקה נפשית",
        "languages": ["עברית", "ערבית", "רוסית", "אנגלית", "אמהרית", "צרפתית", "ספרדית"],
        "referral_process": "חיוג 1201 או פנייה באתר / וואטסאפ. שלוחה 7 לדוברי ערבית.",
        "target_audience": "כלל הציבור, כולל נוער, חרדים, חיילים, עולים וניצולי שואה בקווים ייעודיים",
        "addiction_types": ["mental_health", "dual_diagnosis"],
        "age_group": "all",
        "sector": "general",
        "source_name": "ער״ן",
        "source_url": "https://www.eran.org.il/",
        "notes": "קווי משנה: חרדים 076-8844429; חיילים *2201; עולים *3201; אחרי לידה *9061; ניצולי שואה 1-800-24-1201.",
    },
    {
        "external_id": "seed:natal",
        "name": "נט״ל — נפגעי טראומה נפשית",
        "org_type": "public",
        "kind": "hotline",
        "city": "ארצי",
        "district": "national",
        "phone": "1-800-363-363",
        "website": "https://www.natal.org.il/",
        "hours": "יש לברר באתר / בקו",
        "cost_type": "free",
        "cost_info": "סיוע ראשוני ללא עלות; טיפול בהמשך לפי זכאות",
        "eligibility": "נפגעי טראומה לאומית ובני משפחות",
        "languages": ["עברית"],
        "referral_process": "חיוג לקו או פנייה באתר",
        "target_audience": "נפגעי טראומה, חיילים, אזרחים",
        "addiction_types": ["mental_health"],
        "source_name": "נט״ל",
        "source_url": "https://www.natal.org.il/",
        "sector": "soldiers",
    },
    {
        "external_id": "seed:sahar",
        "name": "סה״ר — סיוע והקשבה ברשת",
        "org_type": "public",
        "kind": "hotline",
        "city": "ארצי",
        "district": "national",
        "phone": "",
        "website": "https://www.sahar.org.il/",
        "hours": "צ׳אט מקוון לפי שעות הפעילות באתר",
        "cost_type": "free",
        "cost_info": "חינם, אנונימי",
        "eligibility": "כל אדם במצוקה",
        "languages": ["עברית"],
        "referral_process": "צ׳אט באתר סה״ר",
        "target_audience": "כלל הציבור, בדגש על בני נוער",
        "addiction_types": ["mental_health", "social_media"],
        "age_group": "all",
        "source_name": "סה״ר",
        "source_url": "https://www.sahar.org.il/",
    },
    {
        "external_id": "seed:health-5400",
        "name": "מוקד קול הבריאות — משרד הבריאות",
        "org_type": "public",
        "kind": "hotline",
        "city": "ארצי",
        "district": "national",
        "phone": "*5400",
        "website": "https://www.gov.il/he/departments/ministry_of_health",
        "hours": "ימי חול, לפי פרסום המשרד",
        "cost_type": "free",
        "eligibility": "כלל הציבור",
        "languages": ["עברית", "ערבית", "רוסית", "אנגלית"],
        "referral_process": "חיוג *5400 לקבלת מידע על שירותי בריאות, כולל התמכרויות ובריאות הנפש",
        "target_audience": "כלל הציבור",
        "addiction_types": ["drugs", "alcohol", "mental_health"],
        "licensing": "משרד הבריאות",
        "source_name": "משרד הבריאות",
        "source_url": "https://www.gov.il/he/departments/ministry_of_health",
        "authority": "moh",
    },
    {
        "external_id": "seed:welfare-local",
        "name": "יחידות לטיפול בנפגעי התמכרויות — רשויות מקומיות",
        "org_type": "public",
        "kind": "welfare_unit",
        "city": "ארצי",
        "district": "national",
        "phone": "",
        "website": "https://www.kolzchut.org.il/he/פנייה_לקבלת_טיפול_בנפגעי_התמכרויות_מטעם_הרשויות_המקומיות",
        "hours": "לפי לשכת הרווחה המקומית",
        "cost_type": "welfare",
        "cost_info": "השתתפות עצמית חודשית (נכון לפרסום כל-זכות: כ-50 ₪). משך טיפול: עד שנתיים לגברים ועד ארבע שנים לנשים.",
        "eligibility": "מכורים לסמים, אלכוהול, הימורים, קניות וגיימינג; פנייה עצמאית או הפניה",
        "languages": ["עברית", "ערבית"],
        "referral_process": "פנייה למחלקה לשירותים חברתיים ברשות המקומית. אבחון, ועדת אבחון והסכם טיפולי לפי תע״ס 11.3.",
        "target_audience": "מבוגרים; חלק מהרשויות מפעילות גם מענים לנוער",
        "addiction_types": ["drugs", "alcohol", "gambling", "shopping", "gaming"],
        "licensing": "משרד הרווחה",
        "source_name": "משרד הרווחה / כל-זכות",
        "source_url": "https://www.kolzchut.org.il/",
        "authority": "molsa",
        "notes": "יש לאתר את היחידה הספציפית לפי עיר המגורים. הפורטל ימלא סניפים מקומיים בסריקות הבאות.",
    },
    {
        "external_id": "seed:aa",
        "name": "AA ישראל — אלכוהוליסטים אנונימיים",
        "org_type": "private",
        "kind": "twelve_step",
        "city": "ארצי",
        "district": "national",
        "phone": "",
        "website": "https://www.aa-israel.org/",
        "hours": "קבוצות לפי לוח באתר",
        "cost_type": "free",
        "cost_info": "ללא עלות, תרומה וולונטרית",
        "eligibility": "כל אדם עם בעיית שתייה",
        "languages": ["עברית", "אנגלית", "רוסית", "ערבית"],
        "referral_process": "הגעה עצמאית לקבוצה לפי לוח האתר; אנונימי",
        "target_audience": "מבוגרים; קיימות גם קבוצות נוער/משפחה בחלק מהמקומות",
        "addiction_types": ["alcohol"],
        "source_name": "AA ישראל",
        "source_url": "https://www.aa-israel.org/",
        "authority": "ngo",
        "confidence": "medium",
    },
    {
        "external_id": "seed:na",
        "name": "NA ישראל — נרקוטיקס אנונימיים",
        "org_type": "private",
        "kind": "twelve_step",
        "city": "ארצי",
        "district": "national",
        "website": "https://www.naisrael.org.il/",
        "hours": "קבוצות לפי לוח באתר",
        "cost_type": "free",
        "eligibility": "כל אדם עם בעיית סמים",
        "languages": ["עברית"],
        "referral_process": "הגעה עצמאית לקבוצה",
        "target_audience": "כלל הציבור",
        "addiction_types": ["drugs"],
        "source_name": "NA ישראל",
        "source_url": "https://www.naisrael.org.il/",
        "authority": "ngo",
        "confidence": "medium",
    },
    {
        "external_id": "seed:ga",
        "name": "GA ישראל — מהמרים אנונימיים",
        "org_type": "private",
        "kind": "twelve_step",
        "city": "ארצי",
        "district": "national",
        "website": "https://www.ga-israel.org/",
        "hours": "קבוצות לפי לוח באתר",
        "cost_type": "free",
        "eligibility": "מהמרים ובני משפחה",
        "languages": ["עברית"],
        "referral_process": "הגעה עצמאית לקבוצה",
        "addiction_types": ["gambling"],
        "source_name": "GA ישראל",
        "source_url": "https://www.ga-israel.org/",
        "authority": "ngo",
        "confidence": "medium",
    },
    {
        "external_id": "seed:sa",
        "name": "SA / קבוצות 12 צעדים להתמכרות מינית",
        "org_type": "private",
        "kind": "twelve_step",
        "city": "ארצי",
        "district": "national",
        "website": "https://www.sa-israel.org/",
        "hours": "קבוצות לפי לוח באתר",
        "cost_type": "free",
        "eligibility": "אנשים המתמודדים עם התמכרות מינית כפייתית",
        "languages": ["עברית"],
        "referral_process": "הגעה עצמאית / בירור באתר",
        "addiction_types": ["sex"],
        "source_name": "SA ישראל",
        "source_url": "https://www.sa-israel.org/",
        "authority": "ngo",
        "confidence": "low",
        "notes": "יש לאמת את כתובת האתר והלוח בסריקה; קבוצות משתנות.",
    },
    {
        "external_id": "seed:mila",
        "name": "מיל״ה — המרכז הישראלי לטיפול בהימורים",
        "org_type": "supervised",
        "kind": "community",
        "city": "ארצי",
        "district": "national",
        "phone": "072-3935365",
        "website": "https://www.milagambling.org.il/",
        "hours": "מרכזים בחיפה ובתל אביב; מענה ארצי",
        "cost_type": "welfare",
        "cost_info": "עלות: יש לברר מול המסגרת",
        "eligibility": "מהמרים, גיימינג ובני משפחה",
        "languages": ["עברית"],
        "referral_process": "פנייה טלפונית למוקד או לאחד ממרכזי חיפה / תל אביב",
        "target_audience": "מבוגרים ובני משפחה; גיימינג והימורים",
        "addiction_types": ["gambling", "gaming", "behavioral"],
        "licensing": "משרד הרווחה / מפעל הפיס",
        "source_name": "מיל״ה",
        "source_url": "https://www.milagambling.org.il/",
        "authority": "molsa",
        "confidence": "high",
        "notes": "פועל במסגרת עמותת הדרך, בפיקוח משרד הרווחה.",
    },
    {
        "external_id": "seed:enosh",
        "name": "אנוש — בריאות הנפש בקהילה",
        "org_type": "public",
        "kind": "ngo",
        "city": "ארצי",
        "district": "national",
        "phone": "*2232",
        "website": "https://www.enosh.org.il/",
        "cost_type": "mixed",
        "eligibility": "מתמודדי נפש ובני משפחה",
        "languages": ["עברית", "ערבית", "רוסית"],
        "referral_process": "פנייה למוקד / סניף מקומי",
        "target_audience": "מתמודדי נפש, משפחות",
        "addiction_types": ["mental_health", "dual_diagnosis"],
        "source_name": "אנוש",
        "source_url": "https://www.enosh.org.il/",
        "authority": "ngo",
        "confidence": "medium",
    },
    {
        "external_id": "seed:elem",
        "name": "אלמ — נוער בסיכון",
        "org_type": "public",
        "kind": "ngo",
        "city": "ארצי",
        "district": "national",
        "phone": "1-800-395-395",
        "website": "https://www.elem.org.il/",
        "cost_type": "free",
        "eligibility": "בני נוער וצעירים בסיכון",
        "languages": ["עברית", "ערבית", "רוסית"],
        "referral_process": "פנייה למוקד או למרכז מקומי",
        "target_audience": "נוער וצעירים",
        "addiction_types": ["drugs", "alcohol", "mental_health", "social_media"],
        "age_group": "youth",
        "source_name": "אלמ",
        "source_url": "https://www.elem.org.il/",
        "authority": "ngo",
        "confidence": "medium",
    },
    {
        "external_id": "seed:clalit-mh",
        "name": "כללית — בריאות הנפש והתמכרויות",
        "org_type": "public",
        "kind": "hmo",
        "city": "ארצי",
        "district": "national",
        "phone": "*2700",
        "website": "https://www.clalit.co.il/",
        "cost_type": "basket",
        "cost_info": "לפי סל הבריאות והשתתפות עצמית של הקופה",
        "eligibility": "מבוטחי כללית",
        "languages": ["עברית", "ערבית", "רוסית"],
        "referral_process": "פנייה לרופא מטפל / מרפאת בריאות הנפש / מוקד הקופה",
        "addiction_types": ["mental_health", "drugs", "alcohol", "dual_diagnosis"],
        "licensing": "משרד הבריאות / קופת חולים",
        "source_name": "כללית",
        "source_url": "https://www.clalit.co.il/",
        "authority": "hmo",
        "confidence": "medium",
    },
    {
        "external_id": "seed:maccabi-mh",
        "name": "מכבי — בריאות הנפש",
        "org_type": "public",
        "kind": "hmo",
        "city": "ארצי",
        "district": "national",
        "phone": "*3555",
        "website": "https://www.maccabi4u.co.il/",
        "cost_type": "basket",
        "eligibility": "מבוטחי מכבי",
        "languages": ["עברית", "רוסית", "ערבית"],
        "referral_process": "מוקד / הפניית רופא / מרפאות בריאות הנפש",
        "addiction_types": ["mental_health", "dual_diagnosis"],
        "source_name": "מכבי",
        "source_url": "https://www.maccabi4u.co.il/",
        "authority": "hmo",
        "confidence": "medium",
    },
    {
        "external_id": "seed:meuhedet-mh",
        "name": "מאוחדת — בריאות הנפש",
        "org_type": "public",
        "kind": "hmo",
        "city": "ארצי",
        "district": "national",
        "phone": "*3833",
        "website": "https://www.meuhedet.co.il/",
        "cost_type": "basket",
        "eligibility": "מבוטחי מאוחדת",
        "languages": ["עברית"],
        "referral_process": "מוקד הקופה / מרפאות",
        "addiction_types": ["mental_health", "dual_diagnosis"],
        "source_name": "מאוחדת",
        "source_url": "https://www.meuhedet.co.il/",
        "authority": "hmo",
        "confidence": "medium",
    },
    {
        "external_id": "seed:leumit-mh",
        "name": "לאומית — בריאות הנפש",
        "org_type": "public",
        "kind": "hmo",
        "city": "ארצי",
        "district": "national",
        "phone": "*507",
        "website": "https://www.leumit.co.il/",
        "cost_type": "basket",
        "eligibility": "מבוטחי לאומית",
        "languages": ["עברית"],
        "referral_process": "מוקד הקופה / מרפאות",
        "addiction_types": ["mental_health", "dual_diagnosis"],
        "source_name": "לאומית",
        "source_url": "https://www.leumit.co.il/",
        "authority": "hmo",
        "confidence": "medium",
    },
    {
        "external_id": "seed:prisoner-rehab",
        "name": "הרשות לשיקום האסיר",
        "org_type": "public",
        "kind": "prison",
        "city": "ארצי",
        "district": "national",
        "website": "https://www.gov.il/he/departments/prisoner_rehabilitation_authority",
        "cost_type": "free",
        "eligibility": "אסירים משוחררים ובני משפחות",
        "languages": ["עברית", "ערבית"],
        "referral_process": "פנייה לרשות / עו״ס שב״ס לקראת שחרור",
        "target_audience": "משוחררים, כולל נפגעי התמכרויות",
        "addiction_types": ["drugs", "alcohol", "mental_health"],
        "source_name": "הרשות לשיקום האסיר",
        "source_url": "https://www.gov.il/he/departments/prisoner_rehabilitation_authority",
        "authority": "gov",
        "confidence": "medium",
    },
]


def seed_if_empty(db: Session) -> int:
    created = 0
    for raw in SEED_SERVICES:
        ext = raw.get("external_id") or ""
        if ext and db.query(Service).filter(Service.external_id == ext).first():
            continue
        svc = _svc(**raw)
        db.add(svc)
        db.flush()
        db.add(
            ServiceSource(
                service_id=svc.id,
                name=svc.source_name or "מאגר בסיס",
                url=svc.source_url,
                authority=svc.authority,
                excerpt="נתוני בסיס לקווי חירום וגופים ארציים. יש לאמת בסריקה מול מקורות רשמיים.",
            )
        )
        created += 1
    if created:
        db.commit()
    return created
